import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import SmoothScrollClient from "@/components/SmoothScrollClient";

export const metadata: Metadata = {
  title: "Gallina Innovations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollClient>
          <PageTransition>{children}</PageTransition>
        </SmoothScrollClient>
      </body>
    </html>
  );
}
